import Head from 'next/head'

import Header from '@/components/Header'

export default function Home() {
  const handleSubmit = (event: any) => {
    event.preventDefault();

    console.log(event.target.club_name.value);
    window.location.href = `/matches/${event.target.club_name.value}`;
  };

  return (
    <>
      <Head>
        <title>Prematch - Content Library</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <header className="bg-zinc-700 shadow">
          <div className="mx-auto max-w-4xl py-6 px-4 sm:px-6 lg:px-8">
            <h1 className="text-3xl font-bold tracking-tight text-white">E-Mail Templates</h1>
          </div>
        </header>
        <main>
          <div className="mx-auto max-w-4xl py-6 sm:px-6 lg:px-8">
            {/* Replace with your content */}
            <div className="px-4 py-6 sm:px-0 bg-zinc-900 rounded-lg max-md:rounded-none">
              <div className="mt-1 px-4">
              <a href="/mail/add">
                <button className="mt-4 px-4 py-2 border rounded-lg text-zinc-950 font-semibold bg-[#FFFF04] border-transparent block hover:bg-[#D9D900] hover:transition-all focus:bg-yellow-400  focus:outline-none focus:ring-2 focus:ring-[#FFFF04] focus:border-transparent w-3/12 max-md:w-full max-md:mr-0 ml-auto mr-0">Template hinzufügen</button>
              </a>
              <div className='bg-zinc-800 rounded-lg p-5 w-6/12'>
                <div className='bg-zinc-700 rounded-lg w-full h-32'>
                </div>
                <p className='mt-4 font-bold'>
                  Title
                </p>
                <p className='mt-1 text-zinc-400'>
                  15.04.2023
                </p>
                <a href="/mail/edit/test">
                  <button className="mt-4 px-4 py-2 w-full border rounded-lg text-zinc-950 font-semibold bg-zinc-200 border-transparent block hover:bg-zinc-300 hover:transition-all focus:bg-zinc-400  focus:outline-none focus:ring-2 focus:ring-zinc-500 focus:border-transparent" type='submit'>Öffnen</button>
                </a>
                </div>
              </div>
            </div>
            {/* /End replace */}
          </div>
        </main>
    </>
  )
}
